---
- name: "Install Ansible Using Pip"
  hosts: host1

  tasks:
          - name: install ansible
            pip:
                    name: virtualenv 

          - name: install ansible
            pip:
                    name: ansible 
                    virtualenv: ~/challenge1