--- 
- 
  hosts: localhost
  name: "make dockers"
  tasks: 
    - 
      docker_container: 
        command: "sleep 1d"
        image: busybox
        name: "busy{{ item }}"
      name: "make dockers"
      with_sequence: count=3
    - 
      add_hosts: 
        ansible_connection: docker
        groups: dockers
        name: "busy{{ item }}"
      name: "add hosts"
      with_sequence: count=3
- 
  hosts: dockers
  name: "Hi from docker"
  tasks: 
    - 
      name: ping
      raw: "echo $HOSTNAME"